# Utilizando node.js em sua versão estável mais recente
language: node_js
node_js:
  - node
# Antes do script instala todos os módulos (yarn é mais rápido que npm)
before_script:
  - yarn install
# Depois de instalar roda o jest com -u para sempre criar uma nova snapshot
script: yarn test -u
